### ISSUE TITLE
bug: Redis URL is not defined for built-in redis chart

### ISSUE THREAD

**Issue by lukasmrtvy** [mvisonneau/helm-charts#10]
Redis URL is not defined for built-in redis chart

Helm output:
```
<.Values.config.redis.url>: nil pointer evaluating interface {}.url
```

Thanks

**Comment by mvisonneau** [comment]
👋 hey @lukasmrtvy, thanks for raising this. It should be fixed with `v0.2.1` 👍

**Comment by lukasmrtvy** [comment]
@mvisonneau thanks 👍 any eta for publishing 0.2.1 chart? thanks

**Comment by mvisonneau** [comment]
looks like there was an issue with the CI, should be released now :+1:

**Comment by lukasmrtvy** [comment]
oh, nice. btw there is another bug, default value for https://github.com/mvisonneau/helm-charts/blob/main/charts/gitlab-ci-pipelines-exporter/templates/secret.yaml#L20 is not defined, fails to  `nil pointer evaluating interface`

**Comment by mvisonneau** [comment]
indeed :facepalm:, just pushed a fix with 0.2.2 :bow:!

**Comment by lukasmrtvy** [comment]
one last thing. redis chart changed some options in values.yaml, these ones are correct for 14.6.1 chart:
```
redis:
  auth:
    enabled: false
  architecture: standalone
```

**Comment by mvisonneau** [comment]
ah cool, thanks for the info!
