### ISSUE TITLE
[gitlab-ci-pipeline-exporter] Configuration Syntax Problem

### ISSUE THREAD

**Issue by djordan41** [mvisonneau/helm-charts#12]
I am using the exporter to pull info from a private gitlab instance, and it "mostly" works, but there seems to be an issue with the config.yaml accepting my configuration changes.  Below is a snippet of my values file as well as the output of my helm template prior to install.  Is there something that I am missing or need to change in order for helm to acknowledge

my values file snippet:
gitlab:
    url: https://gitlab.myorg.org
    token: redacted
    enable_health_check: false
    enable_tls_verify: false
    maximum_requests_per_second: 1

helm template config:
gitlab:
      url: https://gitlab.myorg.org
      maximum_requests_per_second: 1

**Comment by mvisonneau** [comment]
indeed, it is expected for the token to not be present as this one is stored as part of a secret and exposed as a flag. However, there is a bug for the `enable_health_check` and `enable_tls_verify`:  https://github.com/mvisonneau/helm-charts/blob/main/charts/gitlab-ci-pipelines-exporter/templates/_helpers.tpl#L74-L88

**Comment by mvisonneau** [comment]
thanks for reporting this issue @djordan41, hopefully, v0.2.4 should sort it out.

**Comment by djordan41** [comment]
Thank you for the reply!  I will change the _helpers to match what you have in your link and test!
