### ISSUE TITLE
tailscale-relay v0.0.13 is not available

### ISSUE THREAD

**Issue by hadican** [mvisonneau/helm-charts#17]
Hi!

First of all, thank you very much for this chart!

I noticed that the latest chart v0.0.13 is not available on public repo. (https://charts.visonneau.fr)

I recently installed the chart and latest version seems to be v0.0.12 / v1.12.3

<img width="870" alt="Screen Shot 2021-09-15 at 09 33 17" src="https://user-images.githubusercontent.com/10237009/133382931-39afcf4a-b0e0-47ae-a4b1-a605ac0b14c9.png">

**Comment by mvisonneau** [comment]
👋 hey @hadican, thanks for the kind feedback! 🙇 

Indeed the release pipeline seems to have failed for some reason 🤔 https://github.com/mvisonneau/helm-charts/runs/3493929487

I will try to restart it ♻️

**Comment by mvisonneau** [comment]
looks like it passed this time 🎉 , I assume there was some race condition somewhere in the GH release pipeline https://github.com/mvisonneau/helm-charts/runs/3612473073

**Comment by mvisonneau** [comment]
LGTM now, I will therefore close this issue. Thanks for raising it! :bow: 

```
~$ helm search repo mvisonneau/tailscale-relay -l | head -n 3
NAME                      	CHART VERSION	APP VERSION	DESCRIPTION                                  
mvisonneau/tailscale-relay	0.0.13       	v1.14.0    	Deploy a tailscale relay on top of kubernetes
mvisonneau/tailscale-relay	0.0.12       	v1.12.3    	Deploy a tailscale relay on top of kubernetes
```
