### ISSUE TITLE
Adding more than one network to the router?

### ISSUE THREAD

**Issue by Daxcor69** [mvisonneau/helm-charts#19]
variables:
    TAILSCALE_ADVERTISE_ROUTES: 10.245.0.0/16

Could you add a second route?  LIke  10.244.0.0 / 16

I know I can add another whole deployment with the second route, but I thought it would be cool to have just one with two routes

Brad

**Comment by mvisonneau** [comment]
:wave: hey @Daxcor69, I assume you simply have to separate them with a comma :thinking: 

eg: `TAILSCALE_ADVERTISE_ROUTES: 10.245.0.0/16,10.244.0.0/16`
