### ISSUE TITLE
new release version

### ISSUE THREAD

**Issue by crazymushrooms** [mvisonneau/helm-charts#2]
Could you please release a new version of your helm chart?
In the master branch, the dependencies are set up in the Chart.yaml what is compliant with the helm v3.

thank you

**Comment by mvisonneau** [comment]
Which chart are you interested into 🤔 I believe they both got released when the last changes occured though.

**Comment by crazymushrooms** [comment]
I mean "gitlab-ci-pipeline-exporter" :) In the pulled version 0.0.4 the Chart.yaml doesn't contain the "dependencies" block. I suppose it is the reason why the redis dependency is deployed whatever the value "redis.enabled" is set to.
In our case we doesn't need the redis, so we set "redis.enabled=false" in our values file. Nevertheless the redis is deployed.

**Comment by mvisonneau** [comment]
I see, indeed I had to revert to the v1 syntax : https://github.com/mvisonneau/helm-charts/commit/f56e36f25fd5a185b2ec68e6a2f2168b94d26eb2
[0.0.6](https://github.com/mvisonneau/helm-charts/releases/tag/gitlab-ci-pipelines-exporter-0.0.6
) should now be fixing this issue, let me know otherwise!

**Comment by crazymushrooms** [comment]
Many thanks, it works as designed!
