### ISSUE TITLE
[gitlab-ci-pipeline-exporter]: Support to custom resource ServiceMonitor.

### ISSUE THREAD

**Issue by FuyuanChu** [mvisonneau/helm-charts#27]
People may need the ability to relabel metrics, so it's better if we can custom the ServiceMonitor properties.

**Comment by mvisonneau** [comment]
should be fixed through [effddc6](https://github.com/mvisonneau/helm-charts/commit/effddc6dd9c2e7db5a251705e251377102ba4593)
