### ISSUE TITLE
Possible answer to Role TODO

### ISSUE THREAD

**Issue by nathanph** [mvisonneau/helm-charts#31]
I'm not exactly sure what issue you were experiencing, but I found this in the docs and thought it might be of interest to you.

https://github.com/mvisonneau/helm-charts/blob/26ee50744e55d28e53d3034608251c489650d69a/charts/tailscale-relay/templates/role.yaml#L10-L18

From here: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources

>  Note: You cannot restrict create or deletecollection requests by their resource name. For create, this limitation is because the name of the new object may not be known at authorization time. If you restrict list or watch by resourceName, clients must include a metadata.name field selector in their list or watch request that matches the specified resourceName in order to be authorized. For example, kubectl get configmaps --field-selector=metadata.name=my-configmap

**Comment by mvisonneau** [comment]
ohhh, super interesting, thanks a lot for the link @nathanph 🙇 🙏

**Comment by nathanph** [comment]
You're welcome! Cheers!
