### ISSUE TITLE
Bump tailscale to 1.20.2

### ISSUE THREAD

**Issue by Nopzen** [mvisonneau/helm-charts#35]
Using tailscale `tailscale status` it suggest to update version from `1.18.2` -> `1.20.2`.

**Comment by Nopzen** [comment]
tailscale have been updated to 1.22.2, open PR for suggeted fix:

https://github.com/mvisonneau/docker-tailscale/pull/9
https://github.com/mvisonneau/helm-charts/pull/38

**Comment by mvisonneau** [comment]
thanks for these PRs @Nopzen 🙇 !
