### ISSUE TITLE
Enable dnspolicy in tailscale-relay

### ISSUE THREAD

**Issue by steve-winter** [mvisonneau/helm-charts#42]
### Summary
Please can the dnspolicy configuration parameter be added to the tailscale-relay.

### Justification
The existing configuration enables setting the _hostNetwork_ but cannot configure the dnspolicy. Per [documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) the dnspolicy must be explicitly set. At present, in my use case at least, pod fails to start with hostnetwork set, without configuring dnspolicy manually.

> For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
> - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

### Solution
Amend [statefulset.yaml](https://github.com/mvisonneau/helm-charts/blob/main/charts/tailscale-relay/templates/statefulset.yaml) to include dnspolicy alongside the [hostnetwork configuration](https://github.com/mvisonneau/helm-charts/blob/main/charts/tailscale-relay/templates/statefulset.yaml#L27). Possibly also valuable to default the dnspolicy to **ClusterFirstWithHostNet** when hostnetwork is true.

I am happy to create a Pull request, but looking to confirm your agreement before proceeding. And I appreciate the work in the repository to date.

**Comment by mvisonneau** [comment]
hey @steve-winter, sounds good, I implemented it as part of the latest release!
