### ISSUE TITLE
[gitlab-ci-pipelines-exporter] Different apiVersions between chart and Redis dependencies

### ISSUE THREAD

**Issue by paulden** [mvisonneau/helm-charts#5]
Hello,

Thanks for your work on the Gitlab CI Pipelines exporter, this tool is great! :)

I am trying to deploy it using ArgoCD but the Helm binary used to render the chart is based on the `apiVersion`. I noticed the `gitlab-ci-pipelines-exporter` chart is `v1` while its Redis dependency is `v2`, so my issue is that ArgoCD will try to use `helm2` to render the chart but will fail to render the dependency.

I was wondering if there was a specific reason for using `apiVersion: v1` in the chart? Otherwise it would be more consistent to align it with the dependency `apiVersion` (either by making sure it is compatible with Helm2 using an older version of Redis chart or by bumping the `gitlab-ci-pipelines-exporter` apiVersion).

My suggestion is to bump the `gitlab-ci-pipelines-exporter` apiVersion to v2, what do you think?

Thanks again for your work!

Paul

**Comment by mvisonneau** [comment]
:wave: hey @paulden, indeed, thanks for flagging this out. It should be sorted with the [v0.1.5](https://github.com/mvisonneau/helm-charts/releases/tag/gitlab-ci-pipelines-exporter-0.1.5) of the chart! :bow:
