### ISSUE TITLE
ingress chart generic-app networking.k8s.io/v1

### ISSUE THREAD

**Issue by fabiocruzcoelho** [mvisonneau/helm-charts#6]
Chart generic-app does not support kid ingress networking.k8s.io/v1

- Kubernetes v1.120 or major

ingress retorna status code 502

the correction will be carried out, I use your chart for my deploys and the same is very good.

Thanks

**Comment by mvisonneau** [comment]
:wave: hey @fabiocruzcoelho, thanks for flagging this out. I updated it in [v0.0.9](https://github.com/mvisonneau/helm-charts/releases/tag/generic-app-0.0.9) :bow:
