### ISSUE TITLE
[gitlab-ci-pipelines-exporter] install/upgrade failed because label longer than 63 characters

### ISSUE THREAD

**Issue by bt909** [mvisonneau/helm-charts#60]
Hello,

the label `helm.sh/from` can be longer than 63 characters. It is build by `app.fullname` which is truncated to 63 characters, but then a "deploy." is put in front of it, which just exceeds the 63 character limit.

Is it okay to just remove this label, as it is not needed?

e.g: https://github.com/mvisonneau/helm-charts/blob/main/charts/gitlab-ci-pipelines-exporter/templates/deployment.yaml#L23

**Comment by mvisonneau** [comment]
thanks for raising this and providing a fix @bt909. Lets reopen if necessary!
