### ISSUE TITLE
[gitlab-ci-pipelines-exporter] Redis dependency?

### ISSUE THREAD

**Issue by juan-vg** [mvisonneau/helm-charts#68]
- Why is it required? When deploying with docker-compose it's not there
- Why the dependency is it enabled by default? I mean `redis.enabled` in values.yaml
- Why is there no documentation nor any explanation about this requirement?

**Comment by mvisonneau** [comment]
Documentation regarding HA implementation [can be found in the project's README](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/README.md#ha-implementation). If you do not need HA support, feel free to set `redis.enabled=false` and it should still work as expected 👍

**Comment by juan-vg** [comment]
I definitely missed that part. My bad. Thank you for the explanation!
