### ISSUE TITLE
[gitlab-ci-pipelines-exporter] Add ability to set imagePullSecrets

### ISSUE THREAD

**Issue by GDXbsv** [mvisonneau/helm-charts#7]
Because of the request limit on docker hub we are using our own private storage.

Could you please add ability to set `imagePullSecrets` for deployments, so we will be able to add authentication for our registry?

**Comment by mvisonneau** [comment]
:wave: hey @GDXbsv, I added this change as part of  https://github.com/mvisonneau/helm-charts/commit/a0a0ff426a6229a5d27198b2384dab80d7534a75!
