### ISSUE TITLE
New version of helm chart for gitlab-ci-pipelines-exporter 0.5.6

### ISSUE THREAD

**Issue by mklinke** [mvisonneau/helm-charts#81]
First of all, thanks for providing the useful gitlab-ci-pipelines-exporter tool and corresponding helm chart.

I was recently contacted by GitLab support with the recommended action to upgrade to version 0.5.6 of the exporter due to a planned API change on GitLab's side some time this year. 

However, at the time of writing, the latest [helm chart](https://github.com/mvisonneau/helm-charts/blob/main/charts/gitlab-ci-pipelines-exporter/Chart.yaml) still references version 0.5.5.

Are there any plans to update the helm chart in the near future? Anything I could do to help?

Thanks in advance for any update.

Cheers,
Martin

**Comment by patsevanton** [comment]
Any updates?
